#!/bin/bash
source ./lib/functions.sh

# FONT COLORS
define_font_colours

# Welcome
welcome

# SET BASE DIRECTORY
if [[ $(basename "$0") == "setup" ]]; then
  BASE_DIR=$HOME;
else
  BASE_DIR=$PWD/tests/test_home;
fi
PREV_DIR=$(pwd)
cd $BASE_DIR
pwd

# FUNCTION DEFINITIONS

# Return to calling directory
cd $PREV_DIR

# INSTALL PACKAGES
sudo apt update
sudo apt upgrade
sudo apt install build-essential software-properties-common gcc g++ perl make git curl wget gpg net-tools zip unzip ffmpeg ufw openssl dkms ubuntu-restricted-extras python3 htop tmux ca-certificates gnupg
sudo apt autoremove --purge -y

# INSTALL NVM AND NODEJS
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash
nvm install --lts

# INSTALL TMUX PLUGINS
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
## Install plugins by pressing Ctrl+b -> I (capital i, as in Install) in tmux
echo "Please open tmux and press Ctrl+b -> I (capital i, as in Install) to install the plugins. After that, you can exit tmux by typing 'exit' or pressing Ctrl+d."
read -n 1 -s -r -p $'Press any key to continue to launch tmux and install plugins\n'
tmux

if [[ $PREV_DIR == $(pwd) ]]; then
  echo
  echo -e "${GREEN}Thank you for using Uboontup. We hope you had a nice experience.${NC}"
  exit 0;
else
  echo
  echo -e "${RED}We are sorry, but something went wrong.${NC} File an issue or contact us on ${YELLOW}Github${NC} for further assistance."
  exit 1
fi