#!/bin/bash
source ./lib/functions.sh

# FONT COLORS
define_font_colours

# SET BASE DIRECTORY
if [[ $(basename "$0") == "setup" ]]; then
  BASE_DIR=$HOME;
else
  BASE_DIR=$PWD/tests/test_home;
fi
PREV_DIR=$(pwd)
cd $BASE_DIR
pwd

# FUNCTION DEFINITIONS

# Return to calling directory
cd $PREV_DIR

# INSTALL PACKAGES
sudo apt update
sudo apt upgrade
sudo apt install build-essential software-properties-common gcc g++ perl make git curl wget gpg net-tools zip unzip ffmpeg ufw openssl dkms ubuntu-restricted-extras python3 htop tmux
sudo apt autoremove --purge -y

# INSTALL NVM
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.4/install.sh | bash

if [[ $PREV_DIR == $(pwd) ]]; then
  echo -e "${GREEN}Thank you for using Uboontup. We hope you had a nice experience.${NC}"
  exit 0;
else
  echo -e "${RED}We are sorry, but something went wrong.${NC} File an issue or contact us on ${YELLOW}Github${NC} for further assistance."
  exit 1
fi