#!/bin/bash
# Scratchpad for testing functionalities

source ../lib/functions.sh
define_font_colours

recho() {
  echo -e "${RED}$1${NC}"
}

yecho() {
  echo -e "${YELLOW}$1${NC}"
}

gecho() {
  echo -e "${GREEN}$1${NC}"
}

documentation() {
  echo "-----------------------------------------------------"
  echo "|               Welcome to Uboontup !               |"
  echo "|                                                   |"
  echo "|      An easy way to get Ubuntu up and running     |"
  echo "|               for some serious work               |"
  echo "-----------------------------------------------------"

}

enable_bash_customisations() { # Check .bashrc and source for customisation files
  if [[ -z "$ERROR_STRING" ]]; then
    ERROR_STRING="Err"
  fi
  #local BASHRC_FILE="$HOME/.bashrc_test"
  local BASHRC_FILE="./sc_test"
  local CUSTOM_FILE='../custom/uboontup_aliases_and_functions'
  local RGX='source .*uboontup_aliases_and_functions'
  #local LINE='source ../uboontup_aliases_and_functions'
  #local INSERT=""
  local VERSION=$(sed -n 's/.*\(## Uboontup Version: \)\([v\.0-9]*\).*/\2/p' "$CUSTOM_FILE")
  local SOURCES=$(sed -n "/$RGX/p" "$BASHRC_FILE"|wc -l)
  if [[ -f "$BASHRC_FILE" ]]; then
    if [[ ! -z "$TEMP" ]]; then
      echo -e "${YELLOW}Bash customisations found${NC}"
      return 0
    fi
    if [[ "$(ask_confirmation 'Install bash aliases and helper functions to your .bashrc?')" == "y" ]]; then
      echo
      INSERT="\n## Bash customisations (v0.1): aliases and functions\n$LINE"
      echo -e "$INSERT" >> "$BASHRC_FILE"
    else
      echo
      return 0
    fi
  else
    local ERROR_MESSAGE=".bashrc file not found"
    echo -e "${RED}$ERROR_MESSAGE${NC}" >&2
    echo "Please check that you have Bash installed and configured correctly" >&2
    critical_error "$ERROR_MESSAGE"
    return 1
  fi
    # get custom file version
    # if version != current
      # propose to replace lines and file
  # else
    # propose to install
}

edit_line() { # Edit a line in a file. A wrapper around the sed function, taking a search string and replacing it with another insert string in a file. Accepts 3 arguments: 1. the search string; 2. the replacement string; 3. the file to edit. Uses grep with basic regex for line search under the hood and sed for replacement. Returns the number of matches found. Options are: -v (verbose and interactive) to print matches and replacement and require confirmation for replacement; -s (single) for replacement of a single instance of pattern, shifting to interactive mode if multiple instances are found.
  if [[ -z "$ERROR_STRING" ]]; then
    ERROR_STRING="Err"
  fi
  if [[ "$#" -lt 3 ]]; then
    recho "This function requires at least 3 arguments" >&2
    echo "$ERROR_STRING"
    return 1
  fi
  local MODE="n"
  if [[ $4 == "-s" || $5 == "-s" ]]; then
    MODE="s"
  fi
  if [[ $4 == "-v" || $5 == "-v" ]]; then
    MODE="v"
  fi
  if [[ ! -f $3 ]]; then
    recho "$3 is not a regular file" >&2
    echo "$ERROR_STRING"
    return 1
  fi
  local LINE_NUM SEARCH REPLACE NEW_LINE MATCHES CONF REPLACEMENTS
  SEARCH="$1"
  if [[ "$SEARCH" == "\n" ]]; then
    SEARCH=$'\n'
  fi
  REPLACE="$2"
  local LINES="$(grep $SEARCH $3)"
  OLD_IFS=$IFS; IFS=$'\n'; LINES=($LINES); IFS=$OLD_IFS
  MATCHES="${#LINES[@]}"
  if [[ "$MATCHES" -eq 0 ]]; then
    yecho "No match found in file" >&2
    echo "$MATCHES"
    return 0
  fi
  if [[ "$MODE" == 'v' ]]; then
    echo "Matches found:" >&2
    for i in "${!LINES[@]}"; do
      echo "$(( $i + 1 )). ${LINES[$i]}" >&2
    done
  fi
  REPLACEMENTS=0
  for item in "${LINES[@]}"; do
    NEW_LINE=$(sed -n "s/${SEARCH//\//\\/}/${REPLACE//\//\\/}/p" <<< "${item}")
    CONF='y'
    if [[ "$MODE" == 'v' || "$MODE" == "s" ]]; then
      yecho "=====================" >&2
      yecho "Before Edit" >&2
      echo "${item}" >&2
      yecho "After Edit" >&2
      echo "${NEW_LINE}" >&2
      yecho "=====================" >&2
      CONF=$(ask_confirmation)
    fi
    if [[ "$CONF" == 'y' ]]; then
      REPLACEMENTS="$(( ${REPLACEMENTS} + 1 ))"
      sed -i "s/${item//\//\\/}/${NEW_LINE//\//\\/}/" $3
      echo >&2
      if [[ "$MODE" == 's' ]]; then
        break
      fi
    else
      MATCHES="$(( ${MATCHES} - 1 ))"
      echo >&2
    fi
  done
  #cat $3 >&2
  echo >&2
  echo "${REPLACEMENTS}"
  cp sc_test.bak sc_test
}



#documentation
#enable_bash_customisations
#source ./unit_tests/test_check_customisations.sh
#source ./unit_tests/test_edit_line.sh
#source ./unit_tests/test_get_version_score.sh
source ./unit_tests/test_edit_line.sh
#edit_line 'c\(o\?d\?\)e' 'test' 'sc_test' -v
