#!/bin/bash
# Test script to test run installation steps for Uboontup
source ../lib/functions.sh

# FONT COLORS
define_font_colours

# # VARIABLES
UBOON_DIR=$(sed -n 's/\(.*[Uu]boontup\).*/\1/p' <<< $(cd $(dirname "${BASH_SOURCE[0]}") && pwd))
echo "UBOONTUP_DIR=\"$UBOON_DIR\"" > $HOME/.config/uboontup.conf
# USER_DIRS=("logs" "repos" "setup")
# USER_FILES=("/logs/init.log" "/logs/errors.log")
# BASE_DIR="$HOME"
# PREV_DIR="$(pwd)"
# WARNINGS=()
# ERRORS=()

# # Welcome
# welcome

# # enable_bash_customisations
# # Execute actions
# set_base_dir
# check_base_dir
# check_base_dir_write
# # check_and_create_dir "${USER_DIRS[@]}"
# # backup_folder "test" "bkp_"

# cd $PREV_DIR

# # INSTALL PACKAGES
# sudo apt update
# sudo apt upgrade
# sudo apt install build-essential software-properties-common gcc g++ perl make git  curl wget gpg net-tools zip unzip ffmpeg ufw openssl dkms  ubuntu-restricted-extras  python3 htop tmux

# if [[ $PREV_DIR == $(pwd) ]]; then
#   echo -e "${GREEN}Thank you for using Uboontup. We hope you had a nice experience.${NC}"
#   exit 0;
# else
#   echo -e "${RED}We are sorry, but something went wrong.${NC} File an issue or contact us on ${YELLOW}Github${NC} for further assistance."
#   exit 1
# fi
