source ../lib/test.sh
ERROR_STRING="Err"

assert "No version string provided" "$ERROR_STRING" "$(get_version_score)"
assert "Version string with only alphabets" "$ERROR_STRING" "$(get_version_score 'abcdef')"
assert "Version string with only 1 '.'" "$ERROR_STRING" "$(get_version_score '.')"
assert "Version string with only 2 '.'" "$ERROR_STRING" "$(get_version_score '..')"
assert "Version string with only 3 '.'" "$ERROR_STRING" "$(get_version_score '...')"
assert "Version string with only 5 '.'" "$ERROR_STRING" "$(get_version_score '.....')"
assert "Version string with wildcard '*'" "$ERROR_STRING" "$(get_version_score '*')"
assert "Version string with 2 '*'" "$ERROR_STRING" "$(get_version_score '**')"
assert "Version string with 3 '*'" "$ERROR_STRING" "$(get_version_score '***')"
assert "Version string with 5 '*'" "$ERROR_STRING" "$(get_version_score '*****')"
assert "Version string with wildcard '?'" "$ERROR_STRING" "$(get_version_score '?')"
assert "Version string with 2 '??'" "$ERROR_STRING" "$(get_version_score '??')"
assert "Version string with 3 '??'" "$ERROR_STRING" "$(get_version_score '???')"
assert "Version string with 5 '?????'" "$ERROR_STRING" "$(get_version_score '?????')"
assert "Version string with space" "$ERROR_STRING" "$(get_version_score ' ')"
assert "Version string with 2 spaces" "$ERROR_STRING" "$(get_version_score '  ')"
assert "Version string with 5 spaces" "$ERROR_STRING" "$(get_version_score '     ')"
assert "Version string with only 2 components" "$ERROR_STRING" "$(get_version_score ' 1.1')"
assert "Version string, only 2 components, trailing '.'" "$ERROR_STRING" "$(get_version_score ' 1.1.')"
assert "Version string, only 2 components, trailing '*'" "$ERROR_STRING" "$(get_version_score ' 1.1*')"
assert "Version string, only 2 components, trailing '.*'" "$ERROR_STRING" "$(get_version_score ' 1.1.*')"
assert "Version string, only 2 components, trailing '.?'" "$ERROR_STRING" "$(get_version_score ' 1.1.?')"
assert "Version string, only 2 components, trailing '..'" "$ERROR_STRING" "$(get_version_score ' 1.1..')"
assert "Version string with leading space" "$ERROR_STRING" "$(get_version_score ' 1.0.1')"
assert "Version string with trailing space" "$ERROR_STRING" "$(get_version_score '1.0.1 ')"
assert "Version string with space inside" "$ERROR_STRING" "$(get_version_score '1. 0.1')"
assert "Version string with inner '*'" "$ERROR_STRING" "$(get_version_score '1.1*.1')"
assert "Version string with inner '?'" "$ERROR_STRING" "$(get_version_score '1.1?.1')"
assert "Version string with inner '.'" "$ERROR_STRING" "$(get_version_score '1.1..1')"
assert "Version string with only 1 component" "1000000" "$(get_version_score '1')"
assert "Version string with only 1 component and trailing '.'" "$ERROR_STRING" "$(get_version_score '1.')"
assert "Version string with only 1 component and leading '.'" "$ERROR_STRING" "$(get_version_score '.1.')"
assert "Version string with only 2 components" "1002000" "$(get_version_score '1.2')"
assert "Version string with only 2 components and trailing '.'" "$ERROR_STRING" "$(get_version_score '1.2.')"
assert "Version string with only 2 components and leading '.'" "$ERROR_STRING" "$(get_version_score '.1.2')"
assert "Version string with 3 components and trailing '.'" "$ERROR_STRING" "$(get_version_score '1.2.3.')"
assert "Version string with 3 components and leading '.'" "$ERROR_STRING" "$(get_version_score '.1.2.3')"
assert "Version string with 4 components" "$ERROR_STRING" "$(get_version_score '0.1.2.3')"
assert "Version string with 4 '0' components" "$ERROR_STRING" "$(get_version_score '0.0.0.0')"
assert "Version string with 5 components" "$ERROR_STRING" "$(get_version_score '1.2.3.4.5')"
assert "Version string with 5 '0' components" "$ERROR_STRING" "$(get_version_score '0.0.0.0.0')"
assert "Valid version string 1.1.1" "1001001" "$(get_version_score '1.1.1')"
assert "Valid version string 1.2.3" "1002003" "$(get_version_score '1.2.3')"
assert "Valid version string 0.0.0" "0" "$(get_version_score '0.0.0')"
assert "Valid version string 5.2.21(1)-release" "5002021" "$(get_version_score '5.2.21(1)-release')"
assert "Valid version string upper bound 999.999.999" "999999999" "$(get_version_score '999.999.999')"
assert "Valid version string with insane version 3333.2222.1111" "3335223111" "$(get_version_score '3333.2222.1111')"
assert "Valid version string with rc flag" "1002003" "$(get_version_score '1.2.3-rc1')"
assert "Valid version string with alpha flag" "1002003" "$(get_version_score '1.2.3-alpha1.5')"
assert "Valid version string with beta flag" "1002003" "$(get_version_score '1.2.3-beta2.3.4')"
assert "Valid version string with v prefix beta flag" "1002003" "$(get_version_score 'v1.2.3-beta2.3.4')"