source ../lib/test.sh
ERROR_STRING="Err"

assert "No version string provided" "$ERROR_STRING" "$(compare_versions)"
assert "Only 1 Version string provided" "$ERROR_STRING" "$(compare_versions '1.0.0')"
assert "3 invalid version strings provided" "$ERROR_STRING" "$(compare_versions '101' '.0.0' '123')"
assert "3 valid version strings provided" "$ERROR_STRING" "$(compare_versions '1.0.0' '1.1.1' '1.2.2')"
assert "4 valid version strings provided" "$ERROR_STRING" "$(compare_versions '1.0.0' '1.1.1' '1.2.2' '1.3.3')"
assert "1 valid and 1 invalid version string provided" "$ERROR_STRING" "$(compare_versions '1.1.1' '2.2.2.2')"
assert "1 invalid and 1 valid version string provided" "$ERROR_STRING" "$(compare_versions '0.0.0.0' '1.1.1')"
assert "1 valid version string and '.'" "$ERROR_STRING" "$(compare_versions '1.2.3' '.')"
assert "1 valid version string and '*'" "$ERROR_STRING" "$(compare_versions '1.2.3' '*')"
assert "Version string with 3 '*'" "$ERROR_STRING" "$(compare_versions '*.*.*' '1.2.3')"
assert "Version string with 5 '*'" "$ERROR_STRING" "$(compare_versions '0.0.0' '*****')"
assert "Version string with wildcard '?'" "$ERROR_STRING" "$(compare_versions '?' '1.2.3')"
assert "Version string with 3 '??'" "$ERROR_STRING" "$(compare_versions '?.?.?' '0.0.0')"
assert "Version string with 5 '?????'" "$ERROR_STRING" "$(compare_versions '?????' '1.1.1')"
assert "Version strings only space" "$ERROR_STRING" "$(compare_versions ' ' ' ')"
assert "Version strings with only 2 components" "e" "$(compare_versions '1.1' '1.1')"
assert "Version strings, only 2 components, trailing '.'" "$ERROR_STRING" "$(compare_versions '1.1.' '2.2.')"
assert "Version strings, only 2 components, trailing '..'" "$ERROR_STRING" "$(compare_versions '1.1..' '2.2..')"
assert "Version strings, only 2 components, trailing '*'" "$ERROR_STRING" "$(compare_versions ' 1.1.*' '2.2.*')"
assert "3 valid equal version strings 1.1.1" "$ERROR_STRING" "$(compare_versions '1.1.1' '1.1.1' '1.1.1')"
assert "4 valid equal version strings 1.1.1" "$ERROR_STRING" "$(compare_versions '1.1.1' '1.1.1' '1.1.1' '1.1.1')"
assert "Negative version string provided -1.0.0" "$ERROR_STRING" "$(compare_versions '-1.0.0' '0.0.0')"
assert "Negative version string provided -0.0.1" "$ERROR_STRING" "$(compare_versions '-0.0.1' '0.0.0')"
assert "Valid equal version strings 1.1.1" "e" "$(compare_versions '1.1.1' '1.1.1')"
assert "Valid equal version strings 1.0 and 1.0.0" "e" "$(compare_versions '1.1' '1.1.0')"
assert "Valid equal version strings with v prefix v1.1.1" "e" "$(compare_versions 'v1.1.1' 'v1.1.1')"
assert "Valid equal version strings with first v prefix v1.1.1" "e" "$(compare_versions 'v1.1.1' '1.1.1')"
assert "Valid equal version strings with second v prefix v1.1.1" "e" "$(compare_versions '1.1.1' 'v1.1.1')"
assert "Valid equal version strings 0.0.0" "e" "$(compare_versions '0.0.0' '0.0.0')"
assert "Valid equal version strings with rc second v prefix v1.1.1" "e" "$(compare_versions '1.1.1-rc2.0' 'v1.1.1')"
assert "Valid equal version strings with rc second v prefix alpha" "e" "$(compare_versions '1.1.1-rc2.0' 'v1.1.1-alpha1.02df')"
assert "Valid first larger version string v1.1.1" "g" "$(compare_versions 'v1.1.1-rc2.0' 'v1.1.0-rc5')"
assert "Valid first larger version upperbound 1999.1999.1999" "g" "$(compare_versions 'v1999.1999.1999' '1999.1999.1998')"
assert "Valid first larger version with rc" "g" "$(compare_versions 'v1.1.1-rc2.0' 'v1.1.0-rc5')"
assert "Valid first smaller version string v1.1.0" "s" "$(compare_versions 'v1.1.0-rc2.0' 'v1.1.1-rc5')"
assert "Valid first smaller version upperbound 1999.1999.1998" "s" "$(compare_versions 'v1999.1999.1998' '1999.1999.1999')"
assert "Valid first larger version negative string v1.1.1" "s" "$(compare_versions 'v1.02.3-rc2.0' 'v4.5.3-alpha1.05.26')"