source ../lib/test.sh
ERROR_STRING="Err"

assert "No version string provided" "$ERROR_STRING" "$(compare_versions)"
assert "Only 1 Version string provided" "$ERROR_STRING" "$(compare_versions '1.0.0')"
assert "3 invalid version strings provided" "$ERROR_STRING" "$(compare_versions '101' '.0.0' '123')"
assert "3 valid version strings provided" "$ERROR_STRING" "$(compare_versions '1.0.0' '1.1.1' '1.2.2')"
assert "4 valid version strings provided" "$ERROR_STRING" "$(compare_versions '1.0.0' '1.1.1' '1.2.2' '1.3.3')"
assert "1 valid and 1 invalid version string provided" "$ERROR_STRING" "$(compare_versions '1.1.1' '2222')"
assert "1 invalid and 1 valid version string provided" "$ERROR_STRING" "$(compare_versions '0.0.0.0' '1.1.1')"
assert "1 valid version string and '.'" "$ERROR_STRING" "$(compare_versions '1.2.3' '.')"
assert "1 valid version string and '*'" "$ERROR_STRING" "$(compare_versions '1.2.3' '*')"
assert "Version string with 3 '*'" "$ERROR_STRING" "$(compare_versions '*.*.*' '1.2.3')"
assert "Version string with 5 '*'" "$ERROR_STRING" "$(compare_versions '0.0.0' '*****')"
assert "Version string with wildcard '?'" "$ERROR_STRING" "$(compare_versions '?' '1.2.3')"
assert "Version string with 3 '??'" "$ERROR_STRING" "$(compare_versions '?.?.?' '0.0.0')"
assert "Version string with 5 '?????'" "$ERROR_STRING" "$(compare_versions '?????' '1.1.1')"
assert "Version strings only space" "$ERROR_STRING" "$(compare_versions ' ' ' ')"
assert "Version string with only 2 components" "$ERROR_STRING" "$(compare_versions '1.1' '2.2')"
assert "Version string, only 2 components, trailing '.'" "$ERROR_STRING" "$(compare_versions '1.1.' '2.2.')"
assert "Version string, only 2 components, trailing '*'" "$ERROR_STRING" "$(compare_versions ' 1.1.*' '2.2.*')"
assert "3 valid equal version strings 1.1.1" "$ERROR_STRING" "$(compare_versions '1.1.1' '1.1.1' '1.1.1')"
assert "4 valid equal version strings 1.1.1" "$ERROR_STRING" "$(compare_versions '1.1.1' '1.1.1' '1.1.1' '1.1.1')"
assert "Valid equal version strings 1.1.1" "e" "$(compare_versions '1.1.1' '1.1.1')"
assert "Valid equal version strings with v prefix v1.1.1" "e" "$(compare_versions 'v1.1.1' 'v1.1.1')"
assert "Valid equal version strings with first v prefix v1.1.1" "e" "$(compare_versions 'v1.1.1' '1.1.1')"
assert "Valid equal version strings with second v prefix v1.1.1" "e" "$(compare_versions '1.1.1' 'v1.1.1')"
assert "Valid equal version strings 0.0.0" "e" "$(compare_versions '0.0.0' '0.0.0')"
# assert "Valid version string 1.2.3" "1002003" "$(compare_versions '1.2.3')"
# assert "Valid version string 0.0.0" "0" "$(compare_versions '0.0.0')"
# assert "Valid version string upper bound 999.999.999" "999999999" "$(compare_versions '999.999.999')"
# assert "Valid version string with insane version 3333.2222.1111" "3335223111" "$(compare_versions '3333.2222.1111')"